version: "3.9"
services:
  web:
    build: ./gpt-3-api
    ports:
      - "8080:8080"
    volumes:
      - ./gpt-3-api:/usr/src/app
    command: "npm run start:dev"
  redis:
    image: "redis:alpine"
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
