POST http://localhost:8080
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InpZU2UyQk5DLWFNY1Z4NFlfb1ZSeCJ9.eyJpc3MiOiJodHRwczovL2dwdC0zLWF1dGguZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYyZGFmNzRhOGI1MmM3ZjE3MDU5NzFmMiIsImF1ZCI6WyJodHRwczovL2dwdC0zLWRlbW8uY29tIiwiaHR0cHM6Ly9ncHQtMy1hdXRoLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NTg2NzI0MjUsImV4cCI6MTY1ODc1ODgyNSwiYXpwIjoieEl0UjVicXJLbG4yZ0w3cFcwQ2VQVWV4TFBxb3NzMDciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.H__imM0ud9B57z0TjaSoWlWyah83yI51nFZbsX6FhImTk-jOTj67ay0Ok11xRuRSLlD3Gbs28YzTnoIWAodF-73iGnAH0OBLDxAjDKPDgc8qH9g-fWbqusnTHcW6prxuIbY-WnRbZX7aS14re8GSn1dKXVFMWsdCHA-aH0g1dsuWhUn1l6ApEyodhNEXyQM7xuz22mgeFw_KGzs47LFuLK0cM5t2g78tLRUrdEae4yRUD8lHeGpL31ippeUIX1OEnHF9FxgN1RetO1E3xVP3ak1aHW9FyPhTG0mB2KvXKT07pwNg6NxQcC7E1Qiol9nBON1UGhS-QEaXngfOPqBjOw
Content-Type: application/json

{
  "prompt": "Tell me what's up"
}

###

POST http://localhost:4000/recommend-wines
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InpZU2UyQk5DLWFNY1Z4NFlfb1ZSeCJ9.eyJpc3MiOiJodHRwczovL2dwdC0zLWF1dGguZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYyZGFmNzRhOGI1MmM3ZjE3MDU5NzFmMiIsImF1ZCI6WyJodHRwczovL2dwdC0zLWRlbW8uY29tIiwiaHR0cHM6Ly9ncHQtMy1hdXRoLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NTg2NzI0MjUsImV4cCI6MTY1ODc1ODgyNSwiYXpwIjoieEl0UjVicXJLbG4yZ0w3cFcwQ2VQVWV4TFBxb3NzMDciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.H__imM0ud9B57z0TjaSoWlWyah83yI51nFZbsX6FhImTk-jOTj67ay0Ok11xRuRSLlD3Gbs28YzTnoIWAodF-73iGnAH0OBLDxAjDKPDgc8qH9g-fWbqusnTHcW6prxuIbY-WnRbZX7aS14re8GSn1dKXVFMWsdCHA-aH0g1dsuWhUn1l6ApEyodhNEXyQM7xuz22mgeFw_KGzs47LFuLK0cM5t2g78tLRUrdEae4yRUD8lHeGpL31ippeUIX1OEnHF9FxgN1RetO1E3xVP3ak1aHW9FyPhTG0mB2KvXKT07pwNg6NxQcC7E1Qiol9nBON1UGhS-QEaXngfOPqBjOw
Content-Type: application/json

{
  "query": "Spicy cherry flavour"
}
